# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soarya', '0005_auto_20170713_0457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'courses'},
        ),
    ]
