# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 23:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soarya', '0006_auto_20170713_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('link', models.URLField()),
                ('label', models.CharField(blank=True, max_length=50)),
                ('difficulty', models.IntegerField(default=5)),
                ('score', models.IntegerField(default=5)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('valid_date', models.DateTimeField(blank=True)),
                ('comment_num', models.IntegerField(default=0)),
                ('comment_on', models.BooleanField(default=True)),
                ('clicks', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soarya.Category')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soarya.Course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
