# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soarya', '0007_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='author',
        ),
        migrations.RemoveField(
            model_name='source',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='source',
            name='comment_num',
        ),
        migrations.RemoveField(
            model_name='source',
            name='comment_on',
        ),
        migrations.RemoveField(
            model_name='source',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='source',
            name='label',
        ),
        migrations.RemoveField(
            model_name='source',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='source',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='source',
            name='score',
        ),
        migrations.RemoveField(
            model_name='source',
            name='valid_date',
        ),
    ]
