# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 00:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('soarya', '0009_auto_20170713_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='comment_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='comment_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='source',
            name='difficulty',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='source',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 14, 0, 1, 30, 802744, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='source',
            name='score',
            field=models.IntegerField(default=5),
        ),
    ]
