# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 00:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('soarya', '0010_auto_20170714_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name_plural': 'sources'},
        ),
        migrations.AlterField(
            model_name='source',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 14, 0, 3, 43, 771576, tzinfo=utc)),
        ),
    ]
