# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 23:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('soarya', '0014_auto_20170927_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='source',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 27, 23, 13, 48, 55000, tzinfo=utc)),
        ),
    ]
