# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('soarya', '0016_auto_20170927_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='targetname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
