# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soarya', '0017_auto_20170927_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
