# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soarya', '0018_source_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='difficulty',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='source',
            name='score',
            field=models.IntegerField(default=2),
        ),
    ]
