# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soarya', '0019_auto_20170928_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
