# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soarya', '0021_auto_20170929_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='column',
            field=models.IntegerField(default=0),
        ),
    ]
