# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soarya', '0022_course_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='difficulty_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='source',
            name='score_num',
            field=models.IntegerField(default=1),
        ),
    ]
