# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soarya', '0024_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
