# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soarya', '0028_auto_20171013_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='targetname',
            new_name='target',
        ),
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soarya.Source'),
        ),
    ]
