# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_picture'),
        ('soarya', '0029_auto_20171013_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soarya.Source'),
        ),
    ]
