# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soarya', '0030_auto_20171013_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='difficulty',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soarya.Source'),
        ),
    ]
